# Exercise 10: Working with NumPy

NumPy is a python library used for working with (large) n-dimensional arrays. It can be used as you would Excel, operating quickly on rows and columns -- even when your amount of data is **MASSIVE** and would crash your computer if you tried to open it in Excel.

It even has functions for working in the domains of linear algebra and matrix operations!

In [ ]:
import numpy as np

## Creating and reshaping arrays

### Task 1. Create a one dimensional arrar of length 10 filled with integer zeros
Hint: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

```
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

In [ ]:
# YOUR CODE HERE

### Task 2. Create a two dimensional array of size 3x5 filled with floating point ones (i.e. 1.0)
Hint: https://numpy.org/doc/stable/reference/generated/numpy.ones.html

```
 [[1., 1., 1., 1., 1.],
  [1., 1., 1., 1., 1.],
  [1., 1., 1., 1., 1.]]
  ```

In [ ]:
# YOUR CODE HERE

### Task 3. Create a two dimensional array of size 3x5 filled with the number 3.14
Hint: https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full

```
 [[3.14, 3.14, 3.14, 3.14, 3.14],
  [3.14, 3.14, 3.14, 3.14, 3.14],
  [3.14, 3.14, 3.14, 3.14, 3.14]]
```

In [ ]:
# YOUR CODE HERE

### Task 4. Create a 3x3 identity matrix
Hint: https://numpy.org/doc/stable/reference/generated/numpy.identity.html

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 ```

In [ ]:
# YOUR CODE HERE

### Task 5. Create a one dimensional array with 9 elements using numpy's range generator to fill the array with the values 1-9.
Hint: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

```
[1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**!** Save the array as a variable called `A`

In [ ]:
# YOUR CODE HERE

### Task 6. Create a two dimensional array of size 3x3 by reshaping array `A`
Hint: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

**!** Save the array as variable `B`

In [ ]:
# YOUR CODE HERE

### Task 7. Create a two dimensional array of size 3x3 using numpy's random integer generator to fill the values in the array with numbers n, $0 \leq n \leq 10$

Hint: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

```
 [[6, 5, 9],
  [0, 6, 3],
  [6, 4, 2]]
```

Example output -- remember the actual numbers $0 \leq n \leq 10$ will be random

**!** Save the array as variable `C`

In [ ]:
# YOUR CODE HERE

### Task 8. Create a three dimensional array of size 4x3x3 using numpy's random number generator to  fill the values in the array
Hint: https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html

```
[[[8.47479123e-04, 6.77383718e-01, 4.85670390e-01],
   [4.83278589e-01, 6.15245314e-01, 2.11490849e-01],
   [1.49347953e-01, 7.83983365e-01, 5.53822889e-01]],
  [[3.04016610e-01, 6.25469077e-01, 6.48571722e-01],
   [8.63629619e-01, 3.12534574e-01, 3.18482080e-01],
   [4.55083532e-01, 9.85150456e-01, 4.84004643e-01]],
  [[3.43469344e-01, 5.43381121e-01, 2.49079720e-01],
   [6.04169755e-01, 5.95389658e-01, 5.19062476e-01],
   [7.49293335e-01, 5.31758774e-01, 5.41012678e-01]],
  [[4.55190187e-03, 4.95023710e-01, 9.22839467e-01],
   [9.11154749e-01, 8.65357016e-01, 4.74276473e-01],
   [2.86203208e-01, 4.75279571e-01, 7.51917714e-02]]]
```

Example output -- remember the actual numbers $0 \leq n < 1$ will be random

In [ ]:
# YOUR CODE HERE

<font size = 4, color=green>*Do you see the pattern with dimensions and output format?*</font>

## Indexing and slicing arrays

Hints: https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

### Task 9. From the one dimensional array `A`, select elements from index 2 to 4 (including) using array slice operations

The end result should look like this:
```
[3, 4, 5]
```

In [ ]:
# YOUR CODE HERE

### Task 10. From the two dimensional array, `B`, print the value of the 3rd element in the 2nd row using array indexing

Result should be this
```
6
```

In [ ]:
# YOUR CODE HERE

### 10.11. From the two dimensional array, `B`, print the first two elements of each row using array slicing
```
[[1, 2],
 [4, 5],
 [7, 8]]
```

In [ ]:
# YOUR CODE HERE

### Task 12. Create a one dimensional null vector of size 10 and update first the 5th and then the 7th value to be 42 using array indexing

Extra hint: exercise 11.1

Expected result:
```
[ 0.,  0.,  0.,  0., 42.,  0., 42.,  0.,  0.,  0.]
```

**!** Save the array as variable `D`

In [ ]:
# YOUR CODE HERE

## Working with arrays

### Task 13. Find indices of non-zero elements from the array `D`
Hint: https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html
Expected result
```
(array([4, 6]),)
```

In [ ]:
# YOUR CODE HERE

### Task 14. Find the overall minimum and maximum values of the array `B`

Hints: 
- https://numpy.org/doc/stable/reference/generated/numpy.amin.html
- https://numpy.org/doc/stable/reference/generated/numpy.amax.html

Min: `1`
Max: `9`

In [ ]:
# YOUR CODE HERE

### Task 15 Find the minimum and maximum values in each row of the array `B`
Hint: same as 11.4, but with axis

Min: `[1 4 7]`
Max: `[3 6 9]`

In [ ]:
# YOUR CODE HERE

### Task 16 Find the maximum and minimum values in each column of the array `B`
Hint: same as 11.4, but with axis

Min: `[1 2 3]`
Max: `[7 8 9]`

In [ ]:
# YOUR CODE HERE

### Task 17 Find the mean value of the whole array `B`
Hint: https://numpy.org/doc/stable/reference/generated/numpy.mean.html

Expected result
`5.0`

In [ ]:
# YOUR CODE HERE

### Task 18. Check if any of the elements in the arrays `B` and `C` are equal
Hint: https://numpy.org/doc/stable/reference/generated/numpy.equal.html

```
 [[False, False, False],
  [False, False,  True],
  [False, False,  True]]
```
  
Example output -- recall that array C is randomly generated so your result will be different here

In [ ]:
# YOUR CODE HERE

###  Task 19. In place, negate all elements in the array `A` which have a value greater than 6
Hint: https://numpy.org/doc/stable/reference/generated/numpy.where.html

Notice that you can give `np.where` multiple variables to choose from given the condition. For example `np.where(condition, x, y)` where `x` is what happens when condition is `True`, and `y` if otherwise

Expected result:
```
[ 1,  2,  3,  4,  5,  6, -7, -8, -9]
```

In [ ]:
# YOUR CODE HERE

## Linear algebra (try at home if there is not enough time)

### Task 20. Find the dot product of the arrays `B` and `C` (real matrix multiplication)
Hint: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

```
 [[1, 2, 3],           [[3, 8, 4],             [[ 36,  23,  43]
  [4, 5, 6],     ·      [3, 0, 6],       =      [ 81,  62, 100],
  [7, 8, 9]]            [9, 5, 9]]              [126, 101, 157]]
```

Example output -- recall the array C is randomly generated so your result will be different

In [ ]:
# YOUR CODE HERE

### Task 21. Find the determinant of the matrix `B`
Hint: https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html

Expected result:
`0.0`

In [ ]:
# YOUR CODE HERE

### Task 22. Find the transpose of the matrix `B`
Hint: https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

```
B = [[1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]]
```

In [ ]:
# YOUR CODE HERE

### Task 23. Find the inverse of the matrix `C` (first check that its determinant is nonzero)
Hint: https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html

```
 [[-0.16129032, -0.27956989,  0.25806452],
  [ 0.14516129, -0.0483871 , -0.03225806],
  [ 0.08064516,  0.30645161, -0.12903226]
```
  
Example output -- recall that array `C` is randomly generated so your result will be different

In [ ]:
# YOUR CODE HERE